# -*- coding: utf-8 -*-
"""PD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jQm7vIa7QXZj4evPRBby_m2dXGE5AFEL
"""

import datetime
import time
import threading
import json
import sqlite3
from typing import Dict, List, Optional
from dataclasses import dataclass, asdict
from enum import Enum
from datetime import timedelta
import uuid
import calendar

class ExpiryTimer:
    """Класс для отслеживания срока годности с таймером"""

    def __init__(self, product_name: str):
        self.product_name = product_name
        self.timers = []  # Список активных таймеров

    def set_expiry_by_date(self, day: int, month: int, year: int):
        """Установка срока годности по конкретной дате"""
        segodnya = datetime.datetime.today()
        data = datetime.datetime(year, month, day)
        razn = data - segodnya
        sec = razn.total_seconds()

        if sec > 0:
            print(f"📅 Для {self.product_name} осталось {sec:.0f} секунд.")
            print(f"🔔 Напоминание установлено на {data.strftime('%d.%m.%Y')}")

            def konec():
                print(f"\n⚠️⚠️⚠️ ВНИМАНИЕ! Пора выкинуть {self.product_name} ⚠️⚠️⚠️")
                # Здесь можно добавить запись в БД о просрочке

            timer = threading.Timer(sec, konec)
            timer.start()
            self.timers.append(timer)
            return sec
        else:
            print(f"❌ Ошибка: дата {data.strftime('%d.%m.%Y')} уже прошла!")
            return 0

    def set_expiry_by_months(self, months: int):
        """Установка срока годности по количеству месяцев после вскрытия"""
        segodnya = datetime.datetime.today()

        # Используем timedelta
        data = segodnya + timedelta(days=months*30)  # Приблизительно
        razn = data - segodnya
        sec = razn.total_seconds()

        print(f"📅 Для {self.product_name} осталось {sec:.0f} секунд.")
        print(f"🔔 Напоминание установлено на {data.strftime('%d.%m.%Y')}")

        def konec():
            print(f"\n⚠️⚠️⚠️ ВНИМАНИЕ! Пора выкинуть {self.product_name} ⚠️⚠️⚠️")

        timer = threading.Timer(sec, konec)
        timer.start()
        self.timers.append(timer)
        return sec

    def cancel_all_timers(self):
        """Отмена всех таймеров"""
        for timer in self.timers:
            timer.cancel()
        self.timers.clear()
        print(f"✅ Все напоминания для {self.product_name} отменены")

# БЕЗОПАСНАЯ ФУНКЦИЯ ДОБАВЛЕНИЯ МЕСЯЦЕВ

def add_months_to_date(start_date: datetime.date, months: int) -> datetime.date:
    """
    Безопасное добавление месяцев к дате с учетом разного количества дней в месяцах
    """
    year = start_date.year
    month = start_date.month + months

    # Корректировка года
    while month > 12:
        month -= 12
        year += 1

    # Получаем последний день месяца, чтобы избежать ошибки
    last_day = calendar.monthrange(year, month)[1]
    day = min(start_date.day, last_day)

    return datetime.date(year, month, day)

class TesterStatus(Enum):
    AVAILABLE = "available"
    IN_USE = "in_use"
    EXPIRED = "expired"
    EMPTY = "empty"
    MAINTENANCE = "maintenance"

@dataclass
class Tester:
    """Модель тестера с поддержкой таймера (без счетчика использований)"""
    id: str
    product_name: str
    brand: str
    category: str
    opening_date: datetime.date
    expected_lifetime_months: int = 6  # Срок после вскрытия в месяцах
    current_status: TesterStatus = TesterStatus.AVAILABLE
    expiry_timer: Optional[ExpiryTimer] = None

    def __post_init__(self):
        if self.expiry_timer is None:
            self.expiry_timer = ExpiryTimer(self.product_name)

    def get_expiry_date(self) -> datetime.date:
        """Получение даты истечения срока"""
        # Используем безопасную функцию добавления месяцев
        return add_months_to_date(self.opening_date, self.expected_lifetime_months)

    def start_expiry_timer(self):
        """Запуск таймера отсчета до истечения срока"""
        expiry_date = self.get_expiry_date()
        today = datetime.date.today()

        if expiry_date > today:
            self.expiry_timer.set_expiry_by_date(
                expiry_date.day,
                expiry_date.month,
                expiry_date.year
            )
            print(f"⏰ Таймер запущен для {self.product_name} до {expiry_date}")
        else:
            print(f"⚠️ {self.product_name} уже просрочен!")
            self.current_status = TesterStatus.EXPIRED

class IntegratedTesterManager:
    """Управление тестерами с интеграцией вашего таймера"""

    def __init__(self):
        self.testers: Dict[str, Tester] = {}
        self.init_sample_testers()

    def init_sample_testers(self):
        """Инициализация тестеров с запуском таймеров"""
        today = datetime.date.today()

        testers_data = [
            ("T001", "Увлажняющий крем", "Avene", "skincare", today, 6),
            ("T002", "Тональный крем", "Estee Lauder", "makeup", today - datetime.timedelta(days=30), 6),
            ("T003", "Сыворотка с витамином C", "The Ordinary", "skincare", today, 3),  # 3 месяца
            ("T004", "Помада", "MAC", "makeup", today - datetime.timedelta(days=150), 6),
        ]

        for data in testers_data:
            tester = Tester(
                id=data[0],
                product_name=data[1],
                brand=data[2],
                category=data[3],
                opening_date=data[4],
                expected_lifetime_months=data[5]
            )
            self.testers[tester.id] = tester
            # Автоматически запускаем таймер для каждого тестера
            try:
                tester.start_expiry_timer()
            except Exception as e:
                print(f"⚠️ Ошибка при запуске таймера для {tester.product_name}: {e}")

    def add_new_tester_interactive(self):
        """Интерактивное добавление нового тестера (использует ваш код)"""
        print("\n" + "="*60)
        print("➕ ДОБАВЛЕНИЕ НОВОГО ТЕСТЕРА")
        print("="*60)

        # Сбор информации о продукте
        product_name = input("Введите наименование продукта: ")
        brand = input("Введите бренд: ")
        category = input("Введите категорию (skincare/makeup/perfume): ")

        # Ваш код для выбора способа установки срока
        print("\nВыберите способ установки срока годности:")
        print("1 - Указать конкретную дату окончания")
        print("2 - Указать количество месяцев после вскрытия")

        variant = int(input("Ваш выбор (1 или 2): "))

        # Создаем тестер
        tester_id = f"T{datetime.datetime.now().strftime('%Y%m%d%H%M%S')}"
        opening_date = datetime.date.today()

        if variant == 1:
            # Ваш код для ввода даты
            print("\nВведите дату окончания срока годности в формате дд.мм.гггг")
            day = int(input("День: "))
            month = int(input("Месяц: "))
            year = int(input("Год: "))

            # Вычисляем количество месяцев до истечения
            expiry_date = datetime.date(year, month, day)
            # Вычисляем разницу в месяцах
            months_diff = (expiry_date.year - opening_date.year) * 12 + (expiry_date.month - opening_date.month)

            tester = Tester(
                id=tester_id,
                product_name=product_name,
                brand=brand,
                category=category,
                opening_date=opening_date,
                expected_lifetime_months=max(1, months_diff)
            )

        elif variant == 2:
            # Ваш код для ввода месяцев
            months = int(input("Введите количество месяцев: "))
            tester = Tester(
                id=tester_id,
                product_name=product_name,
                brand=brand,
                category=category,
                opening_date=opening_date,
                expected_lifetime_months=months
            )
        else:
            print("❌ ОШИБКА: Неверный выбор!")
            return None

        # Сохраняем и запускаем таймер
        self.testers[tester_id] = tester
        try:
            tester.start_expiry_timer()
            print(f"\n✅ Тестер успешно добавлен!")
            print(f"   ID: {tester_id}")
            print(f"   Истекает: {tester.get_expiry_date()}")
        except Exception as e:
            print(f"\n❌ Ошибка при добавлении тестера: {e}")

        return tester

    def check_all_expiring(self):
        """Проверка всех тестеров на приближение срока годности"""
        print("\n" + "="*60)
        print("🔍 ПРОВЕРКА СРОКОВ ГОДНОСТИ ТЕСТЕРОВ")
        print("="*60)

        today = datetime.date.today()
        expiring_soon = []

        for tester in self.testers.values():
            try:
                expiry = tester.get_expiry_date()
                days_left = (expiry - today).days

                if days_left <= 0:
                    print(f"❌ ПРОСРОЧЕН: {tester.product_name} (просрочен на {-days_left} дней)")
                    tester.current_status = TesterStatus.EXPIRED
                elif days_left <= 30:
                    expiring_soon.append((tester, days_left))
                    print(f"⚠️ СКОРО ПРОСРОЧИТСЯ: {tester.product_name} - осталось {days_left} дней")
                else:
                    print(f"✅ {tester.product_name} - еще {days_left} дней")
            except Exception as e:
                print(f"⚠️ Ошибка при проверке {tester.product_name}: {e}")

        return expiring_soon

    def get_tester_by_name(self, name: str) -> Optional[Tester]:
        """Поиск тестера по названию"""
        for tester in self.testers.values():
            if name.lower() in tester.product_name.lower():
                return tester
        return None

    def manual_check_with_your_code(self):
        """Ручная проверка"""
        print("\n" + "="*60)
        print("🔍 РУЧНАЯ ПРОВЕРКА ПРОДУКТА")
        print("="*60)

        print("Здравствуйте! Введите наименование вашего продукта.")
        product = input()

        # Ищем продукт в системе
        tester = self.get_tester_by_name(product)

        print("Если у вас есть дата окончания срока годности введите 1, если у вас есть количество месяцев после вскрытия товара введите 2.")
        variant = int(input())

        segodnya = datetime.datetime.today()

        if variant == 1:
            print("Введите дату в формате дд.мм.гггг")
            day = int(input("День: "))
            month = int(input("Месяц: "))
            year = int(input("Год: "))
            data = datetime.datetime(year, month, day)
            razn = data - segodnya
            sec = razn.total_seconds()

            if sec > 0:
                print(f"Осталось {sec:.0f} секунд.")
                print(f"{data.strftime('%d.%m.%Y')} - я напомню вам, что следует утилизировать {product}.")

                def konec():
                    print(f"\n⚠️ ПОРА ВЫКИНУТЬ {product} ⚠️")
                    if tester:
                        tester.current_status = TesterStatus.EXPIRED
                        print(f"   Статус в системе обновлен: ПРОСРОЧЕН")

                timer = threading.Timer(sec, konec)
                timer.start()
            else:
                print("❌ Эта дата уже прошла!")

        elif variant == 2:
            print("Введите количество месяцев")
            months = int(input())

            # Используем безопасное добавление месяцев
            expiry_date = add_months_to_date(segodnya.date(), months)
            data = datetime.datetime(expiry_date.year, expiry_date.month, expiry_date.day)
            razn = data - segodnya
            sec = razn.total_seconds()

            if sec > 0:
                print(f"Осталось {sec:.0f} секунд.")
                print(f"{data.strftime('%d.%m.%Y')} - я напомню вам, что следует утилизировать {product}.")

                def konec():
                    print(f"\n⚠️ ПОРА ВЫКИНУТЬ {product} ⚠️")
                    if tester:
                        tester.current_status = TesterStatus.EXPIRED
                        print(f"   Статус в системе обновлен: ПРОСРОЧЕН")

                timer = threading.Timer(sec, konec)
                timer.start()
            else:
                print("❌ Ошибка в расчете даты!")
        else:
            print("ОШИБКА: Неверный выбор!")

    def print_dashboard(self):
        """Вывод дашборда с информацией о таймерах"""
        print("\n" + "="*70)
        print("📊 ДАШБОРД УПРАВЛЕНИЯ ТЕСТЕРАМИ")
        print("="*70)

        today = datetime.date.today()

        for tester in self.testers.values():
            try:
                expiry = tester.get_expiry_date()
                days_left = (expiry - today).days
                status_icon = {
                    TesterStatus.AVAILABLE: "✅",
                    TesterStatus.IN_USE: "🔄",
                    TesterStatus.EXPIRED: "❌",
                    TesterStatus.EMPTY: "📦",
                    TesterStatus.MAINTENANCE: "🔧"
                }.get(tester.current_status, "❓")

                print(f"\n{status_icon} {tester.product_name} ({tester.brand})")
                print(f"   ID: {tester.id}")
                print(f"   Вскрыт: {tester.opening_date}")
                print(f"   Истекает: {expiry} (осталось {days_left} дней)")
                print(f"   Статус: {tester.current_status.value}")
            except Exception as e:
                print(f"\n⚠️ Ошибка при выводе {tester.product_name}: {e}")

# ДЕМОНСТРАЦИЯ РАБОТЫ

def main():
    """Главная функция демонстрации"""

    print("="*70)
    print("🏪 СИСТЕМА УПРАВЛЕНИЯ ТЕСТЕРАМИ")
    print("   С ИНТЕГРАЦИЕЙ ТАЙМЕРА КОНТРОЛЯ СРОКОВ")
    print("="*70)

    manager = IntegratedTesterManager()

    # Показываем текущее состояние
    manager.print_dashboard()

    # Проверяем все сроки
    manager.check_all_expiring()

    # Интерактивное меню
    while True:
        print("\n" + "="*50)
        print("МЕНЮ:")
        print("1 - Добавить новый тестер")
        print("2 - Проверить продукт")
        print("3 - Показать дашборд")
        print("4 - Проверить все сроки")
        print("5 - Выход")

        choice = input("\nВыберите действие: ")

        if choice == "1":
            manager.add_new_tester_interactive()
        elif choice == "2":
            manager.manual_check_with_your_code()
        elif choice == "3":
            manager.print_dashboard()
        elif choice == "4":
            manager.check_all_expiring()
        elif choice == "5":
            print("👋 До свидания!")
            break
        else:
            print("❌ Неверный выбор!")

if __name__ == "__main__":
    main()